// Reconcile checked research into the IF-shaped source registry and review table.
// This publishes no physical figures to the scaffold's cards.
import fs from 'node:fs';
import { BASIS,problems } from '../src/evidence.js';
const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const clusters=[read('research/systems-facts.json'),read('research/physics-facts.json')];
const sources={};const facts=[];
for(const cluster of clusters){
 for(const s of Array.isArray(cluster.sources)?cluster.sources:Object.values(cluster.sources)){
  const verified=s.status==='verified';
  sources[s.id]={title:s.title,publisher:s.publisher,url:s.url,kind:s.kind.toLowerCase(),marketing:s.marketing||false,
   ...(s.published?{published:s.published}:{dated:s.dated||'Publication date not confirmed'}),
   ...(verified?{accessed:s.accessed}:{attempted:s.accessed,unchecked:s.reason||s.note||'Unverified research pointer; not eligible for citation'}),
   status:s.status,...(s.evidence?{evidence:s.evidence}:{}),...(s.section?{section:s.section}:{})};
 }
 for(const f of cluster.facts)facts.push({...f,row:f.row||f.spec});
}
// The seed's alias is not an independent source. Retain it in the audit inventory.
sources['sda-tracking-layer-leo-altitude']={title:'SDA approximate LEO altitude (seed alias)',publisher:'GAO source pointer',url:null,kind:'secondary',dated:'See GAO-26 source record',attempted:'10/01/2026',status:'unchecked',unchecked:'Alias to a contractor-attributed approximate narrative in GAO-26; not adopted as a system orbital specification.'};
let errors=[];
for(const f of facts){const [label,value,basis,ev]=f.row;errors.push(...problems({label,value,basis,ev},sources).map(p=>`${f.id}: ${p}`));}
const seed=fs.readFileSync('research/sources-seed.md','utf8');const ids=[...seed.matchAll(/^### `([^`]+)`/gm)].map(m=>m[1]);for(const id of ids)if(!sources[id])errors.push(`Unreviewed seed ID ${id}`);
if(errors.length)throw new Error(errors.join('\n'));
fs.writeFileSync('src/sources.js','// Generated by node tools/research.mjs; unchecked sources cannot support claims.\nexport const SOURCES = '+JSON.stringify(sources,null,2)+';\nexport const PART_SOURCES = {};\n');
fs.writeFileSync('research/verified-facts.json',JSON.stringify({reviewed:'10/01/2026',scope:'Research for review only. Civil values never describe military systems.',facts},null,2)+'\n');
const levels=[['orbits','The ring'],['satellite','The satellite'],['payload','The payload'],['focal-plane','The focal plane'],['pixel','The pixel'],['plume','The photon / molecular emission'],['ground','Ground segment'],['abi','Civil twin: GOES-R ABI'],['tirs2','Civil twin: Landsat 9 TIRS-2'],['atmosphere','The atmosphere']];
const esc=v=>String(v||'').replaceAll('|','\\|').replaceAll('\n',' ');
let md='# Verified facts by level\n\nReviewed 10/01/2026. Research for Reed’s review; no physical figures are published in the scaffold. Civil figures remain attached to the named instrument. The machine-readable tuples are in `verified-facts.json`; source quotes and access outcomes are in `systems/source-notes.md` and `physics-review.md`.\n';
for(const [id,title]of levels){md+=`\n## ${title}\n\n| Figure or fact | Value | Basis | Evidence / exact location | Scope |\n|---|---|---|---|---|\n`;const rows=facts.filter(f=>f.levels.includes(id));for(const f of rows){const [label,value,basis,ev]=f.row;md+=`| ${esc(label)} | ${esc(value)} | ${BASIS[basis].short} | ${ev.refs.map(([sid,at])=>`[${sid}](${sources[sid].url}), ${esc(at)}`).join('; ')} | ${esc(f.scope||f.qualification)} |\n`;}if(!rows.length)md+='| No verified numerical facts admitted | — | — | See source gaps | Representative only |\n';}
md+='\n## Open gaps\n\n- ABI aperture and standalone detector data rate have not been verified; spacecraft links are not detector data rates.\n- Military hardware dimensions, masses, optical prescription and detector specifics are withheld.\n- No universal detector temperature follows from its material name. T2SL default remains unresolved.\n- No plume intensity, temperature, quantitative atmospheric transmission, or sensor detection-performance model is admitted.\n- Ground depth, HBTSS scope, constellation-position policy, and hero attribution remain Reed’s decisions.\n\n## Seed source audit\n\nEvery named seed record is represented below. Unchecked and pointer records are excluded from all fact references. Historical seed quotations remain preserved as the original handoff, not approved evidence.\n\n| Source ID | Result | Reason if excluded |\n|---|---|---|\n';
for(const id of ids){const s=sources[id];md+=`| ${id} | ${s.status} | ${esc(s.unchecked)} |\n`;}
fs.writeFileSync('research/verified-facts.md',md);
console.log(`${facts.length} checked facts; ${Object.values(sources).filter(s=>s.status==='verified').length} verified sources; ${ids.length} seed records accounted for.`);
