import fs from 'node:fs';
const notice='Personal educational project based on cited public sources. Not an official publication of my employer or of the agencies or companies discussed. Models are schematic; estimates and assumptions are identified.';
const nav=[['index','Story'],['visualizer','Explore'],['evidence','Evidence'],['method','Method'],['glossary','Glossary']];
const levels=['The ring','The satellite','The payload','The focal plane','The pixel','The photon'];
const body={
index:`<p class="eyebrow">Public sources · Infrared · Orbit to pixel</p><h1>The Guardian Ring</h1><p class="lede">A 3D explainer of how overhead persistent infrared satellites observe the Earth, and how observations become warnings.</p><p class="hero-note">${notice}</p><a class="button" href="visualizer.html">Open the explorer →</a><section><p class="kicker">Scaffold preview</p><h2>From the ring to a pixel</h2><p class="lede">The explorer currently holds empty levels. Physical models and figures will follow the source review and look approval.</p><div class="level-grid">${levels.map((t,i)=>`<a href="visualizer.html?view=${i}.light.placeholder"><span>LEVEL ${i+1} · PLACEHOLDER</span><strong>${t}</strong></a>`).join('')}</div></section><section><h2>A traceable explanation</h2><p>Every published figure will identify its source, calculation or assumption. Detailed instrument specifications belong to named civil sensors. The site’s representative hardware will be labeled as drawn.</p><a href="evidence.html">Read the evidence rules →</a></section>`,
evidence:`<p class="eyebrow">Evidence</p><h1>What backs each figure</h1><p class="lede">Sources, calculations and assumptions use the same evidence model in the explorer and on this page.</p><div class="empty">No physical figures are published in the scaffold. Phase 1 research is recorded locally for review before it becomes site content.</div><section><h2>The labels</h2><dl class="basis-list"><dt>Spec</dt><dd>A published specification for a named instrument or standard.</dd><dt>Vendor</dt><dd>A vendor’s attributed comparison, including its baseline.</dd><dt>Reported</dt><dd>A statement in a named public report.</dd><dt>Calc.</dt><dd>A calculation with a formula and traced inputs.</dd><dt>Assumed</dt><dd>An illustrative choice with an explicit reason.</dd></dl></section><section><h2>Source register</h2><p>Verified sources are eligible for a future claim with a precise source location. Unchecked records cannot support a claim.</p><label for="source-search">Filter source records</label><input type="search" id="source-search" placeholder="Title or publisher"><div id="source-register"><p>Research register is being assembled.</p></div></section>`,
method:`<p class="eyebrow">Method</p><h1>Show the reasoning</h1><p class="lede">The model will separate published inputs from calculations and illustrative choices.</p><section><h2>Current scope</h2><p>The scaffold stores scenario choices and tests the viewer contract. It does not yet calculate or display orbital, optical, thermal or detection performance.</p><p>Physical calculations will be implemented only after the source review and look prototype. Civil instrument values will stay attached to the named instrument.</p></section><section id="calculations"><h2>Calculations</h2><p>No physical calculations are enabled.</p></section><section id="assumptions"><h2>Assumptions</h2><p>Placeholder geometry has no physical scale and represents no satellite, telescope or detector. Scenario selections are interface placeholders.</p></section><section><h2>How this is checked</h2><p>Type checks, unit tests and a strict claim audit run alongside browser gates for the parts, framing, controls, camera paths, rendering quality, performance and links.</p></section>`,
glossary:`<p class="eyebrow">Glossary</p><h1>A shared vocabulary</h1><p class="lede">The domain glossary will be written from the verified source notes after review.</p><section><h2>Reading this scaffold</h2><dl class="basis-list"><dt>Level</dt><dd>A place in the planned journey from the whole Earth to a detector element.</dd><dt>Layer</dt><dd>One of the explorer’s Light, Data or Heat views.</dd><dt>Civil twin</dt><dd>A named civil instrument used to explain the underlying engineering with published specifications.</dd><dt>As drawn</dt><dd>A representative illustration whose shape is not a specification.</dd><dt>Unchecked</dt><dd>A source that has not been opened and verified. It cannot support a site claim.</dd></dl></section>`
};
for(const [id,content] of Object.entries(body)){
fs.writeFileSync(id+'.html',`<!doctype html>\n<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex, nofollow"><meta name="description" content="The Guardian Ring: public, cited infrared satellite physics and architecture. Local scaffold awaiting review."><link rel="canonical" href="https://reedos.dev/guardian_ring/${id==='index'?'':id+'.html'}"><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Ccircle cx='16' cy='16' r='11' fill='%230b1015' stroke='%23e6ba82' stroke-width='2'/%3E%3C/svg%3E"><title>${id==='index'?'The Guardian Ring':nav.find(n=>n[0]===id)[1]+' · The Guardian Ring'}</title><link rel="stylesheet" href="/src/pages/site.css"></head><body><a class="skip" href="#main">Skip to content</a><header class="topbar"><a class="brand" href="index.html">The Guardian Ring</a><nav aria-label="Main">${nav.map(([n,t])=>`<a href="${n}.html"${n===id?' aria-current="page"':''}>${t}</a>`).join('')}</nav></header><main id="main">${content}</main><footer><span class="scaffold">LOCAL SCAFFOLD · NOT LAUNCHED</span><p>${notice}</p></footer>${id==='evidence'?'<script type="module" src="/src/pages/evidence.js"></script>':''}<script type="module" src="/src/app/site.js"></script></body></html>\n`);
}
