import fs from 'node:fs';
import { STORY_CLAIMS } from '../src/story-claims.js';
import { SOURCES } from '../src/sources.js';
import { ASSUMPTIONS, BASIS, chip } from '../src/evidence.js';

const notice='Personal educational project based on cited public sources. Not an official publication of my employer or of the agencies or companies discussed. Models are schematic; estimates and assumptions are identified.';
const nav=[['index','Story'],['visualizer','Explore'],['evidence','Evidence'],['method','Method'],['glossary','Glossary']];
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const claimSearch=claim=>[claim.label,claim.value,claim.scope,...(claim.ev?.refs||[]).flatMap(([id,at])=>[id,at,SOURCES[id]?.title,SOURCES[id]?.publisher])].filter(Boolean).join(' ').toLowerCase();
const claims=STORY_CLAIMS.map(claim=>`<article class="claim-row" data-claim-key="${esc(claim.key)}" data-search="${esc(claimSearch(claim))}"><div class="claim-heading"><h3>${esc(claim.label)}</h3>${chip(claim.basis,claim.key,claim.label)}</div><p class="claim-value">${esc(claim.value)}</p><p class="claim-scope">${esc(claim.scope)}</p>${claim.ev?.refs?.length?`<ul class="claim-refs">${claim.ev.refs.map(([id,at])=>`<li><a href="#source-${esc(id)}">${esc(SOURCES[id]?.title||id)}</a><span>${esc(at)}</span></li>`).join('')}</ul>`:`<p class="claim-refs"><a href="method.html#assume-${esc(claim.ev.assume)}">Read the drawing assumptions</a></p>`}</article>`).join('\n');
const sourceRecords=Object.entries(SOURCES).map(([id,source])=>`<article class="source ${source.unchecked?'unchecked':''}" id="source-${esc(id)}" data-source-key="${esc(id)}" data-search="${esc([id,source.title,source.publisher,source.status].join(' ').toLowerCase())}"><p class="kicker">${source.unchecked?'Unchecked · not cited':'Verified public source'}</p><h3>${esc(source.title)}</h3><p>${esc(source.publisher)} · ${esc(source.published||source.dated)} · ${source.unchecked?'Attempted':'Checked'} ${esc(source.accessed||source.attempted)}</p>${source.unchecked?`<p>${esc(source.unchecked)}</p>`:`<a href="${esc(source.url)}" rel="noopener noreferrer" target="_blank">Open source ↗</a>`}</article>`).join('\n');
const assumptions=Object.entries(ASSUMPTIONS).map(([id,assumption])=>`<article class="assumption-row" id="assume-${esc(id)}"><p class="kicker">Assumed</p><h3>${esc(assumption.title)}</h3><p><strong>${esc(assumption.value)}</strong></p><p>${esc(assumption.why)}</p></article>`).join('\n');
const labels=Object.entries(BASIS).filter(([,basis])=>!basis.legacy).map(([,basis])=>`<dt>${esc(basis.short)}</dt><dd>${esc(basis.meaning)}</dd>`).join('');
const body={
 evidence:`<p class="eyebrow">Evidence</p><h1>What backs each figure</h1><p class="lede">The story’s public reference figures and drawing assumptions use the same evidence model as the explorer. Open a label to see the exact source location or assumption.</p><p class="hero-note">${notice}</p><section aria-labelledby="claims-heading"><h2 id="claims-heading">Claims in the look prototype</h2><p>These are published reference values and identified illustration choices. The scenario engine does not calculate physical outputs yet. Civil instrument figures stay attached to the named instrument.</p><label for="claim-search">Find a claim</label><input type="search" id="claim-search" placeholder="Label, value or source" aria-controls="claim-register"><p class="filter-count" id="claim-count" role="status">${STORY_CLAIMS.length} claims</p><div class="claim-register" id="claim-register">${claims}</div><p class="filter-empty" id="claim-empty" hidden>No matching claims.</p></section><section><h2>The labels</h2><dl class="basis-list">${labels}</dl></section><section aria-labelledby="sources-heading"><h2 id="sources-heading">Source register</h2><p>A verified record may support a claim when that claim names the exact passage. Unchecked records are retained for transparency and cannot support a claim.</p><label for="source-search">Filter source records</label><input type="search" id="source-search" placeholder="Title, publisher or source ID" aria-controls="source-register"><p class="filter-count" id="source-count" role="status">${Object.keys(SOURCES).length} source records</p><div id="source-register">${sourceRecords}</div><p class="filter-empty" id="source-empty" hidden>No matching source records.</p></section>`,
 method:`<p class="eyebrow">Method</p><h1>Show the reasoning</h1><p class="lede">Published reference figures, drawing assumptions and future calculations each have a separate record.</p><p class="hero-note">${notice}</p><section><h2>Current scope</h2><p>The story is a static look prototype with Blender-rendered, representative scenes and selected public reference figures. It is ready for visual review. The interactive explorer still contains placeholder scenes.</p><p>The scenario controls store choices and test the viewer contract. They do not calculate orbital, optical, thermal or detection performance. The physics engine comes after the source and look reviews; published civil instrument values remain attached to the named instrument.</p></section><section id="calculations"><h2>Calculations</h2><p>No physical calculations are enabled. The reference figures shown on the story page come directly from their cited public sources.</p><p><a href="evidence.html">Read the claims and their evidence →</a></p></section><section id="assumptions"><h2>Drawing assumptions</h2>${assumptions}<p>The hardware stills use a shared black background, amber light-path highlights and a blue cold-stage color. These colors and the exploded spacing help separate component roles. They do not represent measured temperature, an optical prescription or a real system’s construction.</p><p>The explorer’s placeholder geometry has no physical scale. Its scenario selections remain interface placeholders.</p></section><section><h2>How this is checked</h2><p>Type checks, unit tests and a strict claim audit run alongside browser gates for the parts, framing, controls, camera paths, rendering quality, performance and links. The static look is also checked at desktop and phone sizes.</p></section>`,
 glossary:`<p class="eyebrow">Glossary</p><h1>A shared vocabulary</h1><p class="lede">The domain glossary will be written from the verified source notes after review.</p><section><h2>Reading this scaffold</h2><dl class="basis-list"><dt>Level</dt><dd>A place in the planned journey from the whole Earth to a detector element.</dd><dt>Layer</dt><dd>One of the explorer’s Light, Data or Heat views.</dd><dt>Civil twin</dt><dd>A named civil instrument used to explain the underlying engineering with published specifications.</dd><dt>As drawn</dt><dd>A representative illustration whose shape is not a specification.</dd><dt>Unchecked</dt><dd>A source that has not been opened and verified. It cannot support a site claim.</dd></dl></section>`
};
// The story page is authored independently. Never regenerate or overwrite it.
// Glossary is available explicitly; routine updates touch only these two pages.
const requested=process.argv.slice(2), targets=requested.length?requested:['evidence','method'];
for(const id of targets){
 if(!Object.hasOwn(body,id))throw new Error(`Unsupported page: ${id}; supported pages are evidence, method, glossary`);
 const content=body[id];
 fs.writeFileSync(id+'.html',`<!doctype html>\n<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex, nofollow"><meta name="description" content="The Guardian Ring: public, cited infrared satellite physics and architecture. Local look prototype awaiting review."><link rel="canonical" href="https://reedos.dev/guardian_ring/${id+'.html'}"><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Ccircle cx='16' cy='16' r='11' fill='%230b1015' stroke='%23e6ba82' stroke-width='2'/%3E%3C/svg%3E"><title>${nav.find(n=>n[0]===id)[1]} · The Guardian Ring</title><link rel="stylesheet" href="/src/pages/site.css"></head><body><a class="skip" href="#main">Skip to content</a><header class="topbar"><a class="brand" href="index.html">The Guardian Ring</a><nav aria-label="Main">${nav.map(([n,t])=>`<a href="${n}.html"${n===id?' aria-current="page"':''}>${t}</a>`).join('')}</nav></header><main id="main">${content}</main><footer><span class="scaffold">LOCAL LOOK PROTOTYPE · NOT LAUNCHED</span><p>${notice}</p></footer>${id==='evidence'?'<script type="module" src="/src/pages/evidence.js"></script>':''}<script type="module" src="/src/app/site.js"></script></body></html>\n`);
 console.log(`Wrote ${id}.html`);
}
