// Detector-package anatomy: GOES-R ABI supplies the explicitly named example.
// Drawing choices are independent of the ABI detector package implementation.
const draw = ['Drawing', 'Representative cutaway / not to scale', 'assumed', {assume:'look-model'}];
const role = (label,value,at) => [label,value,'spec',{refs:[['goes-r-databook',at]]}];
const fpm = () => role('ABI focal-plane array','Detector array and associated readout integrated circuit per spectral channel','Printed p. 3-9 / PDF p. 37, Focal Plane Modules and Aft Optics');
const video = () => role('ABI analog path','Focal-plane output to Video Processor','Printed p. 3-9 / PDF p. 37; printed pp. 3-15–3-16 / PDF pp. 43–44, Electronics and Sensor Unit Electronics');
const environment = () => role('ABI aft optics','Windows and cold stops in a controlled cryogenic environment','Printed p. 3-8 / PDF p. 36, Telescope and Aft Optics');
const control = () => role('ABI detector electronics','Timing, bias, and array readout','Printed p. 3-16 / PDF p. 44, Sensor Unit Electronics');
const heat = () => role('ABI heat rejection','Cryocooler, loop heat pipes, radiator','Printed pp. 3-13–3-14 / PDF pp. 41–42, Radiator/Loop Heat Pipe Assembly and Cryocooler');
const mount = () => role('GOES-R ABI mounting','Thermal isolation at titanium mounting feet','Printed p. 14-5 / PDF p. 159, Thermal Control Subsystem');
const part = (id,title,kicker,body,rows=[],drill) => ({id,title,kicker,body,specs:[...rows,draw],...(drill===undefined?{}:{drill})});

export function focalContent() {
  return {
    intro:'A detector package is an optical surface, an electronic assembly, and a thermal load at once. This open teaching assembly separates its cold detector and readout from the warm video electronics. ABI provides the cited civil example; geometry and packaging remain representative.',
    scale:'Detector package · open teaching assembly',
    light:[
      part('array','Detector and readout stack','The image plane','The optical image lands on the detector array. The readout integrated circuit measures the detector signals; it is part of the focal-plane module, rather than the larger warm electronics board beside it. ABI explicitly separates the detector/ROIC module from its video-processing electronics.',[fpm(),video()],4),
      part('shield','Window and cold stop','Control the optical entrance','The aft optics give the detector a controlled optical environment. ABI includes windows and cold stops with its cryogenic focal-plane optics. The open-sided shield shows the idea of defining an entrance around a detector; it is not an ABI enclosure drawing.',[environment()]),
      part('carrier','Carrier and mounting interface','Keep the optical assembly supported','A mount connects the instrument to its supporting structure and is also a thermal interface. GOES-R uses titanium mounting feet to thermally isolate ABI from its platform. The carrier, standoffs, and fasteners drawn here illustrate that support problem at package scale; their materials and spacing are drawing choices.',[mount()]),
      part('flex','Package interconnect','From package to board','The gold ribbon separates the detector package from the board in this drawing. Its bends, contacts, and visible conductors make the connection readable. It illustrates an interconnect without specifying the cable construction used by ABI.'),
      part('readout','Warm video electronics','After the focal-plane module','The detector/ROIC assembly and the warm video board have different jobs. ABI sends analog detector outputs to its Video Processor. The board shows connectors, component packages, and traces so that this next stage has a physical place.',[fpm(),video()],2),
      part('cold-stage','Cold finger and thermal strap','The optical assembly needs cooling','ABI maintains its infrared optical and focal-plane regions at cryogenic temperature. The cold finger and flexible metallic link in the drawing make the connection to refrigeration visible while keeping the optical entrance open.',[environment(),heat()]),
    ],
    data:[
      part('array','Readout integrated circuit','Close to the detector','ABI defines the focal-plane array for each spectral channel as a detector array and associated ROIC. The focal-plane module groups the arrays and filters for a spectral region. This is where detector outputs become an organized electrical readout. The larger board beside the cold plate represents later video processing, not a second detector array.',[fpm()]),
      part('readout','Video processing and conversion','Warm electronics','Analog detector outputs leave the focal-plane module for video processing. ABI’s Sensor Unit Electronics perform analog-to-digital conversion before the data reaches its Electronics Unit for formatting and packetization. Analog conditioning, conversion, and packet handling are separate operations.',[video(),role('ABI digital data path','SUE conversion; Electronics Unit formatting and packetization','Printed pp. 3-15–3-17 / PDF pp. 43–45, Sensor Unit Electronics and Table 3-6')],2),
      part('flex','Signal, bias, and timing connections','More than one electrical role','An array needs controlled bias and timing as well as an output path. ABI’s Sensor Unit Electronics provide these functions. The broad ribbon stands for the package interconnect; visible trace count and routing are illustrative.',[control(),video()]),
      part('shield','Keep optics distinct from readout','A mechanical optical boundary','The shield and optical entrance condition the detector’s environment. They are different from the electronic functions that bias, clock, and read the detector. ABI’s published component descriptions distinguish these optical and electronic responsibilities.',[environment(),control()]),
      part('carrier','Mount the assembly','A supported electrical interface','This drawing puts the package on a carrier and fixes the warm board to a separate tray. Fasteners, strain relief, and connector shells show how the chosen interconnect is held in place. Their number and arrangement are representative drawing choices.'),
      part('cold-stage','Temperature feedback','A control loop alongside the data path','ABI’s cryocooler control electronics use temperature feedback and power-amplifier electronics to regulate cooling. Temperature telemetry is engineering information about the instrument, distinct from the detector’s image data.',[role('ABI cooler control','Temperature feedback and power-amplifier drive','Printed p. 3-17 / PDF p. 45, Cryocooler Control Electronics')],2),
    ],
    heat:[
      part('array','Detector temperature is a design choice','The cold electronic assembly','Cooling can reduce thermal noise. The detector and nearby ROIC are parts of an electronic assembly with a thermal design; a material name alone does not specify its operating temperature. TIRS-2 supplies a separately named civil temperature example.',[fpm(),['Cryogenic cooling','Can reduce thermal noise','reported',{refs:[['nist-cryocooler-2009','PDF p. 2, Table 1']]}]],8),
      part('cold-stage','Heat link to the cooler','A deliberate path','The cold plate connects the package to the illustrated strap and cold finger. In ABI, the cryocooler transfers focal-plane heat toward loop heat pipes and the radiator. The flexible link here represents a thermal connection without assigning its conductance or load.',[heat()]),
      part('shield','Cold optical surroundings','A separate thermal region','ABI’s windows and cold stops belong to its controlled cryogenic optical environment. Keeping that region distinct from warm surrounding equipment is part of the instrument design. Blue in this cutaway identifies a role, not a temperature measurement.',[environment()]),
      part('carrier','Mounting is a thermal interface','Support and isolation','GOES-R’s thermal design isolates ABI at its mounting feet and gives the instrument dedicated heat-rejection hardware. Structural support and intended heat-removal paths therefore need separate treatment. The carrier and standoffs here make those interfaces visible.',[mount(),heat()]),
      part('flex','A physical bridge','Drawn interconnect','The representative ribbon bridges the cold package and warm board. Its physical route is drawn alongside the separate thermal strap to distinguish electrical connection from the intended heat-removal path. No thermal conductance is assigned to the ribbon.'),
      part('readout','Warm board and rejection path','Beyond the cold stage','The video-processing board sits outside the drawn cold enclosure. ABI’s published radiator and loop-heat-pipe assembly rejects instrument heat to space. The separate warm and cold paths show why the board, cooler, and detector should not be treated as a single temperature.',[video(),heat()]),
    ],
  };
}
