// Generated by node tools/research.mjs; unchecked sources cannot support claims.
export const SOURCES = {
  "crs-nc3-primer": {
    "title": "Defense Primer: Nuclear Command, Control, and Communications (NC3)",
    "publisher": "Congressional Research Service",
    "url": "https://www.congress.gov/crs_external_products/IF/PDF/IF11697/IF11697.9.pdf",
    "kind": "primary",
    "marketing": false,
    "published": "01/08/2026 (seed date; not reverified)",
    "attempted": "10/01/2026",
    "unchecked": "Direct web open returned Failed to fetch restricted URL. Stopped; no alternate retrieval.",
    "status": "unchecked"
  },
  "ssc-sbirs-factsheet": {
    "title": "Space Based Infrared System",
    "publisher": "U.S. Space Force",
    "url": "https://www.spaceforce.mil/about-us/fact-sheets/article/2197746/space-based-infrared-system/",
    "kind": "primary",
    "marketing": false,
    "dated": "Publication date not confirmed",
    "attempted": "10/01/2026",
    "unchecked": "Direct web open returned HTTP 403 Forbidden. Stopped; no alternate retrieval.",
    "status": "unchecked"
  },
  "af-sbirs-factsheet-pdf": {
    "title": "Factsheet: Space Based Infrared System (SBIRS)",
    "publisher": "U.S. Air Force / media.defense.gov",
    "url": "https://media.defense.gov/2022/Apr/08/2002973444/-1/-1/1/SBIRS%20FACTSHEET.PDF",
    "kind": "primary",
    "marketing": false,
    "dated": "Publication date not confirmed",
    "attempted": "10/01/2026",
    "unchecked": "Direct web open returned HTTP 403 Forbidden. URL date is not verified document publication date. Stopped; no alternate retrieval.",
    "status": "unchecked"
  },
  "af-sbirs-article": {
    "title": "SBIRS constellation forms under one roof",
    "publisher": "U.S. Air Force",
    "url": "https://www.af.mil/News/Article-Display/Article/566632/sbirs-constellation-forms-under-one-roof/",
    "kind": "primary",
    "marketing": false,
    "dated": "Publication date not confirmed",
    "attempted": "10/01/2026",
    "unchecked": "Direct web open returned HTTP 403 Forbidden. Stopped; no alternate retrieval.",
    "status": "unchecked"
  },
  "ngopir-wikipedia": {
    "title": "Next-Generation Overhead Persistent Infrared",
    "publisher": "Wikipedia",
    "url": "https://en.wikipedia.org/wiki/Next-Generation_Overhead_Persistent_Infrared",
    "kind": "secondary",
    "marketing": false,
    "dated": "Publication date not confirmed",
    "attempted": "10/01/2026",
    "unchecked": "Opened directly. Not an approved primary technical citation; launch chronology remains unverified.",
    "status": "pointer"
  },
  "gao-21-105249": {
    "title": "Missile Warning Satellites: Comprehensive Cost and Schedule Information Would Enhance Congressional Oversight",
    "publisher": "Government Accountability Office",
    "url": "https://www.gao.gov/assets/gao-21-105249.pdf",
    "kind": "primary",
    "marketing": false,
    "published": "09/22/2021",
    "accessed": "10/01/2026",
    "status": "verified",
    "evidence": "research/systems/source-notes.md#gao-21-105249"
  },
  "gao-26-107085": {
    "title": "Missile Warning Satellites: Space Development Agency Should Be More Realistic and Transparent About Risks to Capability Delivery",
    "publisher": "Government Accountability Office",
    "url": "https://files.gao.gov/reports/GAO-26-107085/index.html",
    "kind": "primary",
    "marketing": false,
    "published": "01/28/2026",
    "accessed": "10/01/2026",
    "status": "verified",
    "evidence": "research/systems/source-notes.md#gao-26-107085"
  },
  "sda-tranche1-award": {
    "title": "Space Development Agency Makes Awards for 28 Satellites to Build Tranche 1 Tracking Layer",
    "publisher": "Space Development Agency",
    "url": "https://www.sda.mil/space-development-agency-makes-awards-for-28-satellites-to-build-tranche-1-tracking-layer/",
    "kind": "primary",
    "marketing": false,
    "published": "07/18/2022",
    "accessed": "10/01/2026",
    "status": "verified",
    "evidence": "research/systems/source-notes.md#sda-tranche1-award"
  },
  "sda-tranche1-status-fall2026": {
    "title": "AFA NEWS: First Tranche of Space Development Agency's Missile Tracking Constellation Nearly Complete",
    "publisher": "National Defense / NDIA",
    "url": "https://www.nationaldefensemagazine.org/articles/2026/9/15/space-development-agency-nearing-tranche-1-completion-of-proliferated-warfighter-space-architecture",
    "kind": "secondary",
    "marketing": false,
    "published": "09/15/2026",
    "attempted": "10/01/2026",
    "unchecked": "Opened directly. No technical or operational claims admitted. Seed's specific launch dates not present in opened article.",
    "status": "pointer"
  },
  "mda-hbtss-wikipedia": {
    "title": "Hypersonic and Ballistic Tracking Space Sensor",
    "publisher": "Wikipedia",
    "url": "https://en.wikipedia.org/wiki/Hypersonic_and_Ballistic_Tracking_Space_Sensor",
    "kind": "secondary",
    "marketing": false,
    "dated": "Publication date not confirmed",
    "attempted": "10/01/2026",
    "unchecked": "Opened directly. HBTSS scope remains pending Reed; no technical citation admitted.",
    "status": "pointer"
  },
  "mda-hbtss-factsheet": {
    "title": "HBTSS fact sheet",
    "publisher": "Missile Defense Agency",
    "url": "https://www.mda.mil/global/documents/pdf/hbtss.pdf",
    "kind": "primary",
    "marketing": false,
    "dated": "Publication date not confirmed",
    "attempted": "10/01/2026",
    "unchecked": "Direct web open returned Internal Error with no diagnostic detail. No alternate retrieval. HBTSS scope pending Reed.",
    "status": "unchecked"
  },
  "sda-tracking-layer-overview-search": {
    "title": "SDA Tracking Layer: WFOV vs MFOV design concept",
    "publisher": "Mixed search summaries in seed",
    "url": null,
    "kind": "secondary",
    "marketing": false,
    "dated": "Publication date not confirmed",
    "attempted": "10/01/2026",
    "unchecked": "No concrete source URL in seed; snippets cannot be opened as a source or cited. GAO-26 supplies separately verified architecture context.",
    "status": "unchecked"
  },
  "resilient-meo-mwt-ssc": {
    "title": "The first Medium Earth Orbit Resilient Missile Warning Missile Tracking Program successfully completes its critical design review and goes into production",
    "publisher": "Space Systems Command",
    "url": "https://www.ssc.spaceforce.mil/Portals/3/Documents/PRESS%20RELEASES/The%20first%20Medium%20Earth%20Orbit%20Resilient%20Missile%20Warning%20Missile%20Tracking%20Program%20successfully%20completes%20its%20critical%20design%20review%20and%20goes%20into%20production.pdf",
    "kind": "primary",
    "marketing": false,
    "dated": "Publication date not confirmed",
    "attempted": "10/01/2026",
    "unchecked": "Direct web open returned Internal Error with no diagnostic detail. No alternate retrieval.",
    "status": "unchecked"
  },
  "nga-rmmwt-pe": {
    "title": "PB2024 RDT&E exhibit PE 1206447SF",
    "publisher": "Department of the Air Force; hosted at third-party mirror Velos",
    "url": "https://velosteam.com/wp-content/uploads/2023/04/Line-39_1206447SF_Resilient-Missile-Warning-Missile-Tracking-Medium-Earth-Orbit-MEO.pdf",
    "kind": "primary",
    "marketing": false,
    "dated": "03/2023 (month only on document)",
    "attempted": "10/01/2026",
    "unchecked": "Opened directly; historical document. Official source candidate timed out; mirror fidelity not confirmed, no published claim admitted.",
    "status": "pointer"
  },
  "forge-overview-aggregate": {
    "title": "FORGE overview",
    "publisher": "Mixed search summaries in seed",
    "url": null,
    "kind": "secondary",
    "marketing": false,
    "dated": "Publication date not confirmed",
    "attempted": "10/01/2026",
    "unchecked": "No concrete source URL in seed; snippets cannot be opened as a source or cited. GAO-21 supplies separately verified high-level FORGE role.",
    "status": "unchecked"
  },
  "ssc-obac-forge-release": {
    "title": "Space Systems Command Achieves Operational Acceptance of OPIR Battlespace Awareness Center on FORGE",
    "publisher": "Space Systems Command",
    "url": "https://www.ssc.spaceforce.mil/Portals/3/Documents/PRESS%20RELEASES/Space%20Systems%20Command%20Achieves%20Operational%20Acceptance%20of%20Overhead%20Persistent%20Infrared%20(OPIR)%20Battlespace%20Awareness%20Center%20(OBAC)%20on%20Future%20Operationally.pdf",
    "kind": "primary",
    "marketing": false,
    "dated": "Publication date not confirmed",
    "attempted": "10/01/2026",
    "unchecked": "Direct web open returned Internal Error with no diagnostic detail. No alternate retrieval.",
    "status": "unchecked"
  },
  "official-fy2024-space-force-rdte": {
    "title": "FY2024 Space Force RDT&E Budget Estimates",
    "publisher": "Department of the Air Force",
    "url": "https://www.saffm.hq.af.mil/Portals/84/documents/FY24/Research%20and%20Development%20Test%20and%20Evaluation/FY24%20Space%20Force%20Research%20and%20Development%20Test%20and%20Evaluation.pdf?ver=BQWN2ms9pfLNN_gvIz4mQQ%3D%3D",
    "kind": "primary",
    "marketing": false,
    "dated": "Publication date not confirmed",
    "attempted": "10/01/2026",
    "unchecked": "Direct web open returned HTTP 400 Timeout fetching. No alternate retrieval.",
    "status": "unchecked"
  },
  "goes-r-databook": {
    "title": "GOES-R Series Data Book, Revision A",
    "publisher": "NASA GOES-R Series Program / NOAA OSPO",
    "url": "https://www.ospo.noaa.gov/resources/documents/GOES-RSeriesDataBook.pdf",
    "kind": "primary",
    "marketing": false,
    "dated": "05/2019",
    "accessed": "10/01/2026",
    "status": "verified",
    "section": "Chapter 3, printed pp. 3-8, 3-11, 3-14; PDF pp. 36, 39, 42"
  },
  "noaa-abi-page": {
    "title": "Advanced Baseline Imager (ABI)",
    "publisher": "NOAA/NESDIS",
    "url": "https://www.nesdis.noaa.gov/our-satellites/currently-flying/goes-east-west/advanced-baseline-imager-abi",
    "kind": "primary",
    "marketing": false,
    "dated": "Undated live page",
    "accessed": "10/01/2026",
    "status": "verified",
    "section": "Main instrument description"
  },
  "landsat9-tirs2-nasa": {
    "title": "Thermal Infrared Sensor (TIRS)",
    "publisher": "NASA Science",
    "url": "https://science.nasa.gov/mission/landsat/tirs/",
    "kind": "primary",
    "marketing": false,
    "dated": "Undated live page",
    "accessed": "10/01/2026",
    "status": "verified",
    "section": "Design; Spectral Bands"
  },
  "nasa-tirs2-build": {
    "title": "TIRS-2 Testing: A Landsat 9 Instrument Takes Shape",
    "publisher": "NASA Landsat Project Science Support",
    "url": "https://science.nasa.gov/missions/landsat/tirs-2-testing-a-landsat-9-instrument-takes-shape/",
    "kind": "primary",
    "marketing": false,
    "dated": "03/01/2018",
    "accessed": "10/01/2026",
    "status": "verified",
    "section": "Instrument design paragraphs following test photographs"
  },
  "nasa-tirs2-spectral": {
    "title": "Landsat 9 Thermal Infrared Sensor 2 Subsystem-Level Spectral Test Results",
    "publisher": "NASA NTRS / instrument team",
    "url": "https://ntrs.nasa.gov/api/citations/20180004892/downloads/20180004892.pdf",
    "kind": "primary",
    "marketing": false,
    "dated": "2018",
    "accessed": "10/01/2026",
    "status": "verified",
    "section": "PDF p. 1, Introduction"
  },
  "nasa-irdetectors-ntrs": {
    "title": "Infrared Detectors Overview in the Short Wave Infrared to Far Infrared for CLARREO Mission",
    "publisher": "NASA Langley / NTRS",
    "url": "https://ntrs.nasa.gov/api/citations/20100030592/downloads/20100030592.pdf",
    "kind": "primary",
    "marketing": false,
    "dated": "2010 (PDF creation metadata; exact publication date unconfirmed)",
    "accessed": "10/01/2026",
    "status": "verified",
    "section": "PDF pp. 3-7, sections A.1-A.3 and Table 1"
  },
  "nist-cryocooler-2009": {
    "title": "Cryocoolers: the state of the art and recent developments",
    "publisher": "NIST / Ray Radebaugh",
    "url": "https://tsapps.nist.gov/publication/get_pdf.cfm?pub_id=901013",
    "kind": "primary",
    "marketing": false,
    "dated": "03/31/2009",
    "accessed": "10/01/2026",
    "status": "verified",
    "section": "PDF p. 4, section 4"
  },
  "nist-refrigeration-2020": {
    "title": "Review of Refrigeration Methods (submitted chapter)",
    "publisher": "NIST / Ray Radebaugh",
    "url": "https://trc.nist.gov/cryogenics/Papers/Review/2020-Review_of_Refrigeration_Methods.pdf",
    "kind": "primary",
    "marketing": false,
    "dated": "2020 (submitted version)",
    "accessed": "10/01/2026",
    "status": "verified",
    "section": "PDF pp. 2-3, equation (1) and following paragraph"
  },
  "nasa-combustion-bands": {
    "title": "Determination of primary-zone smoke concentrations from spectral radiance measurements in gas turbine combustors",
    "publisher": "NASA Lewis / Carl T. Norgren",
    "url": "https://ntrs.nasa.gov/api/citations/19710021767/downloads/19710021767.pdf",
    "kind": "primary",
    "marketing": false,
    "dated": "07/1971",
    "accessed": "10/01/2026",
    "status": "verified",
    "section": "Printed p. 5; PDF p. 7, gaseous combustion products paragraph"
  },
  "nasa-atmospheric-windows": {
    "title": "Remote Sensing",
    "publisher": "NASA Earth Observatory",
    "url": "https://science.nasa.gov/earth/earth-observatory/remote-sensing/",
    "kind": "primary",
    "marketing": false,
    "dated": "09/17/1999",
    "accessed": "10/01/2026",
    "status": "verified",
    "section": "Absorption Bands and Atmospheric Windows"
  },
  "nasa-orbit-catalog": {
    "title": "Catalog of Earth Satellite Orbits",
    "publisher": "NASA Earth Observatory",
    "url": "https://science.nasa.gov/earth/earth-observatory/catalog-of-earth-satellite-orbits/",
    "kind": "primary",
    "marketing": false,
    "dated": "09/04/2009",
    "accessed": "10/01/2026",
    "status": "verified",
    "section": "High Earth Orbit; Medium Earth Orbit"
  },
  "noaa-geo-definition": {
    "title": "Geostationary Earth Orbit Satellite (GEO)",
    "publisher": "NOAA CoastWatch",
    "url": "https://coastwatch.noaa.gov/cwn/platform-types/geostationary-earth-orbit-satellite-geo.html",
    "kind": "primary",
    "marketing": false,
    "dated": "Undated live page",
    "accessed": "10/01/2026",
    "status": "verified",
    "section": "Definition paragraph"
  },
  "bams-abi-paper": {
    "title": "A Closer Look at the ABI on the GOES-R Series",
    "publisher": "AMS BAMS / Schmit et al.",
    "url": "https://journals.ametsoc.org/view/journals/bams/98/4/bams-d-15-00230.1.xml",
    "kind": "primary",
    "marketing": false,
    "dated": "2017",
    "attempted": "10/01/2026",
    "unchecked": "Fresh direct web request returned HTTP 403 Forbidden. Stopped this source and reported it; no alternate tool or mirror retry. Not cited by any fact.",
    "status": "unchecked"
  },
  "detector-operating-temps-aggregate": {
    "kind": "secondary",
    "marketing": false,
    "dated": "Publication date not confirmed",
    "attempted": "10/01/2026",
    "unchecked": "Original snippet mixture has no page URLs. Specific civil examples are verified separately; no universal HgCdTe/InSb/QWIP/T2SL default was established.",
    "status": "unchecked"
  },
  "plume-ir-emission-aggregate": {
    "kind": "secondary",
    "marketing": false,
    "dated": "Publication date not confirmed",
    "attempted": "10/01/2026",
    "unchecked": "Original snippet mixture has no page URLs. Generic H2O/CO2 bands are supported by an opened NASA combustion paper; no rocket intensity or temperature was established.",
    "status": "unchecked"
  },
  "atmospheric-windows-aggregate": {
    "kind": "secondary",
    "marketing": false,
    "dated": "Publication date not confirmed",
    "attempted": "10/01/2026",
    "unchecked": "Original snippet mixture has no page URLs. General absorption/window definitions are verified separately; numeric window boundaries and transmission remain unverified.",
    "status": "unchecked"
  },
  "cryocooler-aggregate": {
    "kind": "secondary",
    "marketing": false,
    "dated": "Publication date not confirmed",
    "attempted": "10/01/2026",
    "unchecked": "Original snippet mixture has no page URLs. NIST review PDFs were resolved, opened, downloaded and quoted directly; original aggregate is not a citation.",
    "status": "unchecked"
  },
  "orbit-definitions-aggregate": {
    "kind": "secondary",
    "marketing": false,
    "dated": "Publication date not confirmed",
    "attempted": "10/01/2026",
    "unchecked": "Original snippet mixture has no page URLs. Recommended NASA catalog opened directly, and NOAA confirms GEO altitude; original aggregate is not a citation.",
    "status": "unchecked"
  },
  "sda-tracking-layer-leo-altitude": {
    "title": "SDA approximate LEO altitude (seed alias)",
    "publisher": "GAO source pointer",
    "url": null,
    "kind": "secondary",
    "dated": "See GAO-26 source record",
    "attempted": "10/01/2026",
    "status": "unchecked",
    "unchecked": "Alias to a contractor-attributed approximate narrative in GAO-26; not adopted as a system orbital specification."
  }
};
export const PART_SOURCES = {};
